# Generated by Django 5.2.1 on 2025-06-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoEDUplatform', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coursess',
        ),
    ]
