# Generated by Django 5.1.3 on 2025-06-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoEDUplatform', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='esewa_id',
            field=models.IntegerField(null=True),
        ),
    ]
