# Generated by Django 5.2.1 on 2025-06-17 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoEDUplatform', '0005_paymentplans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentplans',
            name='plan_type',
        ),
    ]
